HW5: mystring.c File Reference
mystring.c File Reference
#include <string.h>
#include <stdlib.h>
#include "mystring.h"
Functions
char * mystrdup (const char *src)
char * mychardup (const char *src)
char * mystrndup (const char *src, size_t n)
The mystrndup() function returns a pointer to a new string which is a duplicate up to n chars of the string src. Memory for the new string is obtained malloc() and can be freed with free().
int mystrlen (const char *src)
Calculates the length of the string pointed to by src excluding the null terminator.
char * mystrcpy (char *des, const char *src)
The mystrcpy() function copies the string pointed to by src, including the null byte ('\0') to the buffer pointed to by des. The strings may not overlap and the destination string must be large enough to receive the copy.
char * mystrncpy (char *des, const char *src, size_t n)
The mystrncpy() function copies the first n chars in string pointed to by src, including If the length of src is less than n, mystrncpy() writes additional null bytes to des to ensure that a total of n bytes are written.
char * mystrcat (char *des, const char *src)
the mystrcat() function appends the src string to the des string, overwriting the terminating null byte ('\0') at the end of des, and then adding a terminating null byte. The strings may not overlap and the des string must have enough space for the result. If the des is not large enough, program behavior is unpredictable
char * mystrncat (char *des, const char *src, size_t n)
Function Documentation
mychardup()
char* mychardup (const char * src)
References mystrncpy().
Referenced by main().
mystrcat()
char* mystrcat (char * des, const char * src)
the mystrcat() function appends the src string to the des string, overwriting the terminating null byte ('\0') at the end of des, and then adding a terminating null byte. The strings may not overlap and the des string must have enough space for the result. If the des is not large enough, program behavior is unpredictable
Parameters
des string receiving the append
src string to append
Returns
char* returns pointer of string
References mystrlen().
mystrcpy()
char* mystrcpy (char * des, const char * src)
The mystrcpy() function copies the string pointed to by src, including the null byte ('\0') to the buffer pointed to by des. The strings may not overlap and the destination string must be large enough to receive the copy.
Author
Cristobal Rincon Rogers
Parameters
des pointer where string will be copied to
src pointer to string to copy
Returns
char* return buffer pointer containing the copy of the string
Referenced by mystrdup().
mystrdup()
char* mystrdup (const char * src)
mystring.c
Authors
Mike Ciaraldi, Blake Nelson, Cristobal Rincon Rogers Custom versions of some of the C-style string functions Duplicates a C-style string.
Parameters
src Pointer to string to be copied
Returns
Pointer to freshly-allocated string containing a duplicate of src or null if no memory is available
References mystrcpy(), and mystrlen().
Referenced by main().
mystrlen()
int mystrlen (const char * src)
Calculates the length of the string pointed to by src excluding the null terminator.
Author
Cristobal Rincon Rogers
Parameters
src pointer to the string we want to find the length of
Returns
int returns the number of bytes in the string pointed to by src
Referenced by mystrcat(), mystrdup(), mystrncat(), and mystrndup().
mystrncat()
char* mystrncat (char * des, const char * src, size_t n)
References mystrlen().
mystrncpy()
char* mystrncpy (char * des, const char * src, size_t n)
The mystrncpy() function copies the first n chars in string pointed to by src, including If the length of src is less than n, mystrncpy() writes additional null bytes to des to ensure that a total of n bytes are written.
Author
Cristobal Rincon Rogers
Warning
If there is no null byte among the first n bytes of src, the string placed in des will not be null terminated
Parameters
des pointer where string will be copied to
src pointer to string to copy
n number of chars to copy
Returns
char* pointer to destination string
Referenced by mychardup(), and mystrndup().
mystrndup()
char* mystrndup (const char * src, size_t n)
The mystrndup() function returns a pointer to a new string which is a duplicate up to n chars of the string src. Memory for the new string is obtained malloc() and can be freed with free().
Warning
if src is longer than n, only n bytes are copied, and a terminating null byte ('\0') is added
Parameters
src
Returns
char*
References mystrlen(), and mystrncpy().