lab2: at3.c File Reference
at3.c File Reference
#include "print_arrays.h"
#include "array_sort.h"
#include <stdlib.h>
#include <stdio.h>
Macros
#define SAMPLE_INT_ARRAY_SIZE (10)
Functions
int generateRandom (int max)
void populate_arr_with_rand (int maxCount, int maxRandom, int *des)
int main (int argc, const char *argv[])
Macro Definition Documentation
SAMPLE_INT_ARRAY_SIZE
#define SAMPLE_INT_ARRAY_SIZE (10)
file at2.c @Cristobal Rincon Rogers
Program to print arrays entered in the command line.
Function Documentation
generateRandom()
int generateRandom (int max)
Main program for printing arrays. It fills them with floats entered through the command line and prints them.
Parameters
argc Number of entries in the command line
argv Array of
Returns
0, Indicating success.
Referenced by populate_arr_with_rand().
main()
int main (int argc, const char * argv[])
References populate_arr_with_rand(), print_int_array(), and sort_array_int().
populate_arr_with_rand()
void populate_arr_with_rand (int maxCount, int maxRandom, int * des)
References generateRandom().
Referenced by main().