lab2: print_arrays.h File Reference
print_arrays.h File Reference
Functions
void print_int_array (int a[], int size)
void print_double_array (double a[], int size)
int insert_double_into (int inputs, const char **src, double *des, int length)
This function inserts floats entered from the command line, converts them to doubles, and copies the doubles into another array.
Function Documentation
insert_double_into()
int insert_double_into (int inputs, const char ** src, double * des, int length)
This function inserts floats entered from the command line, converts them to doubles, and copies the doubles into another array.
Parameters
inputs the number of inputs entered from the command line
src the values entered from the command line that we wish to convert and copy
des the array where the values from src get inserted into
length the length of the des array
Returns
int value of 0 indicates success
Referenced by main().
print_double_array()
void print_double_array (double a[], int num_entries)
Print an array of doubles, one per line.
Parameters
a Array to print of doubles
num_entries Number of entries in the array
Referenced by main().
print_int_array()
void print_int_array (int a[], int num_entries)
File print_arrays.c
Author
Cristobal Rincon Rogers
Header file for functions that print arrays.
file print_arrays.c
Author
Cristobal Rincon Rogers
Functions for printing arrays. Print an array of ints, one per line.
Parameters
a Array to print
num_entries Number of entries in the array
Referenced by main().