hw3: employee.c File Reference
employee.c File Reference
employee.c allows for manipulation of employee structs.
#include <stdio.h>
#include <stdlib.h>
#include "mystring.h"
#include "employee.h"
#include "generate.h"
Functions
Employee * make_employee (char *name, int birth_year, int start_year)
Allocates a struct of type Employee and fills it with data passed as parameters.
void printEmployee (Employee *employee)
the printEmployee() function prints the elements of the employee struc
unsigned char validate (char *name)
the validate() function verifies that a name is within the max employee name and null terminates
Employee * generateEmployee (int nameLength)
the generateEmployee() function auto populates an Employee with random values
Employee ** generateWorkforce (int size)
the generateWorkforce() function generates an array of pointers to Employees of a desired size
void printWorkforce (Employee **work, int size)
the printWorkforce() function prints an array of Employees
Employee ** copyWorkforce (Employee **work, int size)
the copyWorkforce() function shallow copies an existing array of Employee pointers
void freeTheEmployees (Employee **work, int size)
the freeTheEmployees() function frees allocated memory created with malloc()
Employee ** deepCopyWorkforce (Employee **work, int size)
the deepCopyWorkforce() function deep copies an existing array of Employee. This function returns an array of new Employee pointers with the copied content inside the structs.
Detailed Description
employee.c allows for manipulation of employee structs.
Author
Cristobal Rincon Rogers
Version
0.1
Date
2023-02-08
Copyright
Copyright (c) 2023
Function Documentation
copyWorkforce()
Employee** copyWorkforce (Employee ** work, int size)
the copyWorkforce() function shallow copies an existing array of Employee pointers
Parameters
work array of Employee pointers
size number of elements in array of Employee pointers
Returns
Employee** array of shallow copied Employee pointers
Referenced by main().
deepCopyWorkforce()
Employee** deepCopyWorkforce (Employee ** work, int size)
the deepCopyWorkforce() function deep copies an existing array of Employee. This function returns an array of new Employee pointers with the copied content inside the structs.
Parameters
work array of employee pointers
size number of elements in Employee pointers
Returns
Employee** array of deep copied Employee pointers
References _employee::birth_year, make_employee(), _employee::name, and _employee::start_year.
Referenced by main().
freeTheEmployees()
void freeTheEmployees (Employee ** work, int size)
the freeTheEmployees() function frees allocated memory created with malloc()
Parameters
work array of Employee pointers
size number of elements in array of Employee pointers
Referenced by main().
generateEmployee()
Employee* generateEmployee (int nameLength)
the generateEmployee() function auto populates an Employee with random values
Parameters
nameLength desired length of employee name
Returns
Employee* pointer to newly created employee
References generateStr(), generateYear(), and make_employee().
Referenced by generateWorkforce(), and main().
generateWorkforce()
Employee** generateWorkforce (int size)
the generateWorkforce() function generates an array of pointers to Employees of a desired size
Parameters
size length of array
Returns
Employee** array of Employee pointers
References generateEmployee().
Referenced by main().
make_employee()
Employee* make_employee (char * name, int birth_year, int start_year)
Allocates a struct of type Employee and fills it with data passed as parameters.
Author
Cristobal Rincon Rogers
Parameters
name a character array containing the name of the employee. Max name is 20 characters.
birth_year int describing the employee birth year
start_year int describing the year the employee began working at that company
Returns
Employee* pointer to Employee struct in heap
References _employee::birth_year, _employee::name, _employee::start_year, and validate().
Referenced by deepCopyWorkforce(), generateEmployee(), and main().
printEmployee()
void printEmployee (Employee * employee)
the printEmployee() function prints the elements of the employee struc
Parameters
employee pointer to employee struct
References _employee::birth_year, _employee::name, and _employee::start_year.
Referenced by main(), and printWorkforce().
printWorkforce()
void printWorkforce (Employee ** work, int size)
the printWorkforce() function prints an array of Employees
Parameters
work array of Employee pointers
size number of elements in array of Employee pointers
References printEmployee().
Referenced by main().
validate()
unsigned char validate (char * name)
the validate() function verifies that a name is within the max employee name and null terminates
Parameters
name pointer to string
Returns
unsigned char returns boolean value. 1: name is valid. 0: name is invalid.
References MAX_EMPLOYEE_NAME_LENGTH, and mystrlen().
Referenced by make_employee().