hw3: generate.h File Reference
generate.h File Reference
generate.h contains defined constants and function prototypes for generate.c
Macros
#define MAX_CHAR_RANGE 'z'
#define LOWER_NUMERIC_RANGE '0'
#define UPPER_NUMERIC_RANGE '9'
#define LOWER_UPPERCASE_RANGE 'A'
#define UPPER_UPPERCASE_RANGE 'Z'
#define LOWER_LOWERCASE_RANGE 'a'
#define UPPER_LOWERCASE_RANGE 'z'
Functions
char generateChar ()
the generateChar() function generates an alphanumeric character of value: 0-9, A-Z, a-z
char * generateStr (int length)
the generateStr() function generates random string of a specified length.
int generateYear ()
the generateYear() function returns a random year between 0 and 2023.
Detailed Description
generate.h contains defined constants and function prototypes for generate.c
Author
Cristobal Rincon Rogers
Version
0.1
Date
2023-02-08
Copyright
Copyright (c) 2023
Macro Definition Documentation
LOWER_LOWERCASE_RANGE
#define LOWER_LOWERCASE_RANGE 'a'
LOWER_NUMERIC_RANGE
#define LOWER_NUMERIC_RANGE '0'
LOWER_UPPERCASE_RANGE
#define LOWER_UPPERCASE_RANGE 'A'
MAX_CHAR_RANGE
#define MAX_CHAR_RANGE 'z'
UPPER_LOWERCASE_RANGE
#define UPPER_LOWERCASE_RANGE 'z'
UPPER_NUMERIC_RANGE
#define UPPER_NUMERIC_RANGE '9'
UPPER_UPPERCASE_RANGE
#define UPPER_UPPERCASE_RANGE 'Z'
Function Documentation
generateChar()
char generateChar ()
the generateChar() function generates an alphanumeric character of value: 0-9, A-Z, a-z
Returns
char an alphanumeric character
References LOWER_LOWERCASE_RANGE, LOWER_NUMERIC_RANGE, LOWER_UPPERCASE_RANGE, MAX_CHAR_RANGE, UPPER_LOWERCASE_RANGE, UPPER_NUMERIC_RANGE, and UPPER_UPPERCASE_RANGE.
Referenced by generateStr().
generateStr()
char* generateStr (int length)
the generateStr() function generates random string of a specified length.
Parameters
length desired length of string.
Returns
char* pointer to the string
References generateChar().
Referenced by generateEmployee().
generateYear()
int generateYear ()
the generateYear() function returns a random year between 0 and 2023.
Returns
int year between 0 and 2023.
Referenced by generateEmployee().