hw3: generate.c File Reference
generate.c File Reference
generate.c creates characters, strings, and integers at random.
#include <stdio.h>
#include <stdlib.h>
#include "generate.h"
Functions
char generateChar ()
the generateChar() function generates an alphanumeric character of value: 0-9, A-Z, a-z
char * generateStr (int length)
the generateStr() function generates random string of a specified length.
int generateYear ()
the generateYear() function returns a random year between 0 and 2023.
Detailed Description
generate.c creates characters, strings, and integers at random.
Author
Cristobal Rincon Rogers
Version
0.1
Date
2023-02-08
Copyright
Copyright (c) 2023
Function Documentation
generateChar()
char generateChar ()
the generateChar() function generates an alphanumeric character of value: 0-9, A-Z, a-z
Returns
char an alphanumeric character
References LOWER_LOWERCASE_RANGE, LOWER_NUMERIC_RANGE, LOWER_UPPERCASE_RANGE, MAX_CHAR_RANGE, UPPER_LOWERCASE_RANGE, UPPER_NUMERIC_RANGE, and UPPER_UPPERCASE_RANGE.
Referenced by generateStr().
generateStr()
char* generateStr (int length)
the generateStr() function generates random string of a specified length.
Parameters
length desired length of string.
Returns
char* pointer to the string
References generateChar().
Referenced by generateEmployee().
generateYear()
int generateYear ()
the generateYear() function returns a random year between 0 and 2023.
Returns
int year between 0 and 2023.
Referenced by generateEmployee().